#ifndef GSV2K11_RXDIG_MAP_FCT_H
#define GSV2K11_RXDIG_MAP_FCT_H
#define GSV2K11_RXDIG_get_RB_RX_TMDS_PLL_LOCKED(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x80, 0x7, pval)
#define GSV2K11_RXDIG_get_RB_RX_HDMI_MODE(gsv_config,port, pval)                    AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x20, 0x5, pval)
#define GSV2K11_RXDIG_get_RB_RX_VS_LOCKED(gsv_config,port, pval)                    AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x10, 0x4, pval)
#define GSV2K11_RXDIG_get_RB_RX_HS_LOCKED(gsv_config,port, pval)                    AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x8, 0x3, pval)
#define GSV2K11_RXDIG_get_RB_RX_AUDIO_LAYOUT(gsv_config,port, pval)                 AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x2, 0x1, pval)
#define GSV2K11_RXDIG_get_RB_RX_AVMUTE_STATE(gsv_config,port, pval)                 AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x00, 0x1, 0x0, pval)
#define GSV2K11_RXDIG_get_RB_RX_DEEP_COLOR_MODE(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x03, 0x30, 4, pval)
#define GSV2K11_RXDIG_get_RB_RX_PIXEL_REPETITION(gsv_config,port, pval)             AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x03, 0xF, 0, pval)
#define GSV2K11_RXDIG_get_RB_RX_AUDIO_N(gsv_config,port, pval)                      AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x09, 0xF, 0xFF, 0, 3, pval)
#define GSV2K11_RXDIG_get_RB_RX_HS_POL(gsv_config,port, pval)                       AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x0C, 0x80, 0x7, pval)
#define GSV2K11_RXDIG_get_RB_RX_VS_POL(gsv_config,port, pval)                       AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x0C, 0x40, 0x6, pval)
#define GSV2K11_RXDIG_get_RB_RX_INTERLACED(gsv_config,port, pval)                   AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x0C, 0x20, 0x5, pval)
#define GSV2K11_RXDIG_get_RB_RX_H_ACTIVE_WIDTH(gsv_config,port, pval)               AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x0C, 0x1F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_V_ACTIVE_HEIGHT_0(gsv_config,port, pval)            AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x0E, 0x1F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RX_REPETITION_MAN_EN(gsv_config,port, pval)               AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x12, 0x10, 0x4, pval)
#define GSV2K11_RXDIG_get_RX_REPETITION_MAN(gsv_config,port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x12, 0xF, 0, pval)
#define GSV2K11_RXDIG_get_RX_AUDIO_MCLK_X_N(gsv_config,port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x14, 0x7, 0, pval)
#define GSV2K11_RXDIG_set_RX_AUDIO_MCLK_X_N(gsv_config,port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x14, 0x7, 0, val)
#define GSV2K11_RXDIG_set_DCFIFO_RECENTER(gsv_config,port, val)                     AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x22, 0x4, 0x2, val)
#define GSV2K11_RXDIG_get_RB_RX_H_TOTAL_WIDTH(gsv_config,port, pval)                AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x26, 0x3F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_H_FRONT_PORCH(gsv_config,port, pval)                AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x28, 0x1F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_H_SYNC_WIDTH(gsv_config,port, pval)                 AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x2A, 0x1F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_H_BACK_PORCH(gsv_config,port, pval)                 AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x2C, 0x1F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_V_TOTAL_0(gsv_config,port, pval)                    AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x2E, 0x3F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_V_FRONT_PORCH_0(gsv_config,port, pval)              AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x32, 0x3F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_V_SYNC_WIDTH_0(gsv_config,port, pval)               AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x36, 0x3F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_RB_RX_V_BACK_PORCH_0(gsv_config,port, pval)               AvHalI2cReadField32BE(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x3A, 0x3F, 0xFF, 0, 2, pval)
#define GSV2K11_RXDIG_get_VPLL_MANUAL_MODE(gsv_config,port, pval)                   AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x5D, 0x40, 0x6, pval)
#define GSV2K11_RXDIG_set_VPLL_MANUAL_MODE(gsv_config,port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x5D, 0x40, 0x6, val)
#define GSV2K11_RXDIG_set_N_CTS_STABLE_DET_START(gsv_config,port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x7A, 0x2, 0x1, val)
#define GSV2K11_RXDIG_get_RX_APLL_MAN_START_CALC(gsv_config,port, pval)             AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x7A, 0x1, 0x0, pval)
#define GSV2K11_RXDIG_set_RX_APLL_MAN_START_CALC(gsv_config,port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0x7A, 0x1, 0x0, val)
#define GSV2K11_RXDIG_set_ECC_AVMUTE_MAN_EN(gsv_config,port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xBE, 0x10, 0x4, val)
#define GSV2K11_RXDIG_get_RX_SCDC_TMDS_BIT_CLK_RATIO_MAN_EN(gsv_config,port, pval)  AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x80, 0x7, pval)
#define GSV2K11_RXDIG_set_RX_SCDC_TMDS_BIT_CLK_RATIO_MAN_EN(gsv_config,port, val)   AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x80, 0x7, val)
#define GSV2K11_RXDIG_get_RX_SCDC_TMDS_BIT_CLK_RATIO_MAN(gsv_config,port, pval)     AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x40, 0x6, pval)
#define GSV2K11_RXDIG_set_RX_SCDC_TMDS_BIT_CLK_RATIO_MAN(gsv_config,port, val)      AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x40, 0x6, val)
#define GSV2K11_RXDIG_get_RX_SCDC_SCR_EN_MAN_EN(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x20, 0x5, pval)
#define GSV2K11_RXDIG_set_RX_SCDC_SCR_EN_MAN_EN(gsv_config,port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x20, 0x5, val)
#define GSV2K11_RXDIG_get_RX_SCDC_SCR_EN_MAN(gsv_config,port, pval)                 AvHalI2cReadField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x10, 0x4, pval)
#define GSV2K11_RXDIG_set_RX_SCDC_SCR_EN_MAN(gsv_config,port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_RXDIG_MAP_ADDR(port), 0xD9, 0x10, 0x4, val)
#endif
