#ifndef GSV2K11_TXCEC_MAP_FCT_H
#define GSV2K11_TXCEC_MAP_FCT_H
#define GSV2K11_TXCEC_set_CEC_TX_FRAME_LENGTH(gsv_config,port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x10, 0x1F, 0, val)
#define GSV2K11_TXCEC_get_CEC_TX_ENABLE(gsv_config,port, pval)                      AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x11, 0x1, 0x0, pval)
#define GSV2K11_TXCEC_set_CEC_TX_ENABLE(gsv_config,port, val)                       AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x11, 0x1, 0x0, val)
#define GSV2K11_TXCEC_set_CEC_TX_RETRY(gsv_config,port, val)                        AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x12, 0x70, 4, val)
#define GSV2K11_TXCEC_get_TX_LOWDRIVE_COUNTER(gsv_config,port, pval)                AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x14, 0xF0, 4, pval)
#define GSV2K11_TXCEC_get_CEC_TX_NACK_COUNTER(gsv_config,port, pval)                AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x14, 0xF, 0, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF0_FRAME_LENGTH(gsv_config,port, pval)           AvHalI2cReadField8(ggsv_config,sv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x25, 0x1F, 0, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF2_TIMESTAMP(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x26, 0x30, 4, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF1_TIMESTAMP(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x26, 0xC, 2, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF0_TIMESTAMP(gsv_config,port, pval)              AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x26, 0x3, 0, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF1_FRAME_LENGTH(gsv_config,port, pval)           AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x37, 0x1F, 0, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF2_FRAME_LENGTH(gsv_config,port, pval)           AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x48, 0x1F, 0, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF2_READY(gsv_config,port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x49, 0x4, 0x2, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF1_READY(gsv_config,port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x49, 0x2, 0x1, pval)
#define GSV2K11_TXCEC_get_CEC_RX_BUF0_READY(gsv_config,port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x49, 0x1, 0x0, pval)
#define GSV2K11_TXCEC_set_CEC_RX_3BUFFERS_ENABLE(gsv_config,port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4A, 0x8, 0x3, val)
#define GSV2K11_TXCEC_set_CEC_RX_CLEAR_BUF2(gsv_config,port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4A, 0x4, 0x2, val)
#define GSV2K11_TXCEC_set_CEC_RX_CLEAR_BUF1(gsv_config,port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4A, 0x2, 0x1, val)
#define GSV2K11_TXCEC_set_CEC_RX_CLEAR_BUF0(gsv_config,port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4A, 0x1, 0x0, val)
#define GSV2K11_TXCEC_get_CEC_LOGIC_ADDR_SELECTION(gsv_config,port, pval)           AvHalI2cReadField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4B, 0x70, 4, pval)
#define GSV2K11_TXCEC_set_CEC_LOGIC_ADDR_SELECTION(gsv_config,port, val)            AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4B, 0x70, 4, val)
#define GSV2K11_TXCEC_set_CEC_LOGIC_ADDR1(gsv_config,port, val)                     AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4C, 0xF0, 4, val)
#define GSV2K11_TXCEC_set_CEC_LOGIC_ADDR0(gsv_config,port, val)                     AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4C, 0xF, 0, val)
#define GSV2K11_TXCEC_set_CEC_LOGIC_ADDR2(gsv_config,port, val)                     AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4D, 0xF, 0, val)
#define GSV2K11_TXCEC_set_CEC_POWER_MODE(gsv_config,port, val)                      AvHalI2cWriteField8(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x4E, 0x3, 0, val)
#define GSV2K11_TXCEC_set_CEC_PHY_ADDR(gsv_config,port, val)                        AvHalI2cWriteField32BE(gsv_config,GSV2K11_TXCEC_MAP_ADDR(port), 0x80, 0xFF, 0xFF, 0, 2, val)
#endif
