#ifndef GSV2K11_TXDIG_MAP_FCT_H
#define GSV2K11_TXDIG_MAP_FCT_H
#define GSV2K11_TXDIG_set_TX_AUDIO_MODE(gsv_config,port, val)                       AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x00, 0xE0, 5, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_ENCODE_STYLE(gsv_config,port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x00, 0x18, 3, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_MCLK_FS_RATIO(gsv_config,port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x00, 0x6, 1, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_SPDIF_ENABLE(gsv_config,port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x01, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_EXT_MCLK_ENABLE(gsv_config,port, val)            AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x01, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_OVERRIDE(gsv_config,port, val)                AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x02, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_I2S_BLOCK_ENABLE(gsv_config,port, val)           AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x02, 0x3C, 2, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_I2S_FORMAT(gsv_config,port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x02, 0x3, 0, val)
#define GSV2K11_TXDIG_get_TX_AUDIO_SPDIF_SF_RB(gsv_config,port, pval)               AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x04, 0xF, 0, pval)
#define GSV2K11_TXDIG_set_TX_AUDIO_PAPB_SYNC(gsv_config,port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x10, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_FORMAT_EXTRA(gsv_config, port, val)            AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x15, 0x38, 3, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_COPYRIGHT(gsv_config, port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x15, 0x4, 0x2, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_FORMAT(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x15, 0x3, 0, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_CATEGORY_CODE(gsv_config, port, val)           AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x16, 0xFF, 0, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_SOURCE_NUMBER(gsv_config, port, val)           AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x17, 0xF, 0, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_MODE(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x18, 0x30, 4, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_I2S_MAN_SF(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x18, 0xF, 0, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_CS_WORD_LENGTH(gsv_config, port, val)             AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x19, 0xF, 0, val)
#define GSV2K11_TXDIG_set_TX_AUDIO_LAYOUT_MAN_VALUE(gsv_config, port, val)           AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1A, 0x40, 0x6, val)
#define GSV2K11_TXDIG_get_TX_AUDIO_MUTE(gsv_config, port, pval)                      AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1A, 0x20, 0x5, pval)
#define GSV2K11_TXDIG_set_TX_AUDIO_MUTE(gsv_config, port, val)                       AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1A, 0x20, 0x5, val)
#define GSV2K11_TXDIG_set_TX_MUX_MODE_AVMUTE_MAN(gsv_config, port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1E, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_MUX_MODE_AVMUTE_MAN_EN(gsv_config, port, val)           AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1E, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_MAN_POL_HS(gsv_config, port, val)                          AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1F, 0x2, 0x1, val)
#define GSV2K11_TXDIG_set_MAN_POL_VS(gsv_config, port, val)                          AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x1F, 0x1, 0x0, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_INPUT_FORMAT(gsv_config, port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x20, 0xF0, 4, val)
#define GSV2K11_TXDIG_get_TX_VIDEO_INPUT_CS(gsv_config, port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x20, 0x8, 0x3, pval)
#define GSV2K11_TXDIG_set_TX_VIDEO_INPUT_CS(gsv_config, port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x20, 0x8, 0x3, val)
#define GSV2K11_TXDIG_get_TX_VIDEO_OUTPUT_FORMAT(gsv_config, port, pval)             AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x21, 0xC0, 6, pval)
#define GSV2K11_TXDIG_set_TX_VIDEO_OUTPUT_FORMAT(gsv_config, port, val)              AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x21, 0xC0, 6, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_ASPECT_RATIO(gsv_config, port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x22, 0x2, 0x1, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_PR_MODE(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x23, 0xC0, 6, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_TMDS_CLK_RATIO_MAN(gsv_config, port, val)         AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x23, 0x30, 4, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_PR_TO_RX_MAN(gsv_config, port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x23, 0xC, 2, val)
#define GSV2K11_TXDIG_get_TX_VIDEO_CSC_ENABLE(gsv_config, port, pval)                AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x2B, 0x80, 0x7, pval)
#define GSV2K11_TXDIG_set_TX_VIDEO_CSC_ENABLE(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x2B, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_VIDEO_CSC_SCALING_FACTOR(gsv_config, port, val)         AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x2B, 0x60, 5, val)
#define GSV2K11_TXDIG_get_TX_BLACK_VIDEO_EN(gsv_config, port, pval)                  AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x4E, 0x8, 0x3, pval)
#define GSV2K11_TXDIG_set_TX_BLACK_VIDEO_EN(gsv_config, port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x4E, 0x8, 0x3, val)
#define GSV2K11_TXDIG_set_TX_AUDIOFIFO_RESET(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x4F, 0x1, 0x0, val)
#define GSV2K11_TXDIG_set_TX_PKT_MPEG_ENABLE(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x50, 0x10, 0x4, val)
#define GSV2K11_TXDIG_set_TX_PKT_AUDIO_INFO_ENABLE(gsv_config, port, val)            AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x50, 0x8, 0x3, val)
#define GSV2K11_TXDIG_set_TX_PKT_SPDIF_ENABLE(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x50, 0x4, 0x2, val)
#define GSV2K11_TXDIG_set_TX_PKT_AVIIF_PKT_ENABLE(gsv_config, port, val)             AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x50, 0x2, 0x1, val)
#define GSV2K11_TXDIG_set_TX_PKT_VSIF_ENABLE(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x50, 0x1, 0x0, val)
#define GSV2K11_TXDIG_set_TX_PKT_USER1_ENABLE(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_PKT_USER0_ENABLE(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_TX_PKT_GM_ENABLE(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x20, 0x5, val)
#define GSV2K11_TXDIG_set_TX_PKT_ISRC_ENABLE(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x10, 0x4, val)
#define GSV2K11_TXDIG_set_TX_PKT_ACP_ENABLE(gsv_config, port, val)                   AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x8, 0x3, val)
#define GSV2K11_TXDIG_set_TX_PKT_GC_ENABLE(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x4, 0x2, val)
#define GSV2K11_TXDIG_get_TX_PKT_AUDIO_SAMPLE_ENABLE(gsv_config, port, pval)         AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x2, 0x1, pval)
#define GSV2K11_TXDIG_set_TX_PKT_AUDIO_SAMPLE_ENABLE(gsv_config, port, val)          AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x2, 0x1, val)
#define GSV2K11_TXDIG_set_TX_PKT_N_CTS_ENABLE(gsv_config, port, val)                 AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x51, 0x1, 0x0, val)
#define GSV2K11_TXDIG_set_TX_GC_CLEAR_AVMUTE(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x52, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_GC_SET_AVMUTE(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x52, 0x40, 0x6, val)
#define GSV2K11_TXDIG_get_TX_GC_CD(gsv_config, port, pval)                           AvHalI2cReadField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x53, 0xF, 0, pval)
#define GSV2K11_TXDIG_set_TX_GC_CD(gsv_config, port, val)                            AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0x53, 0xF, 0, val)
#define GSV2K11_TXDIG_set_TX_HDMI_MODE_OVERRIDE(gsv_config, port, val)               AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xA5, 0x80, 0x7, val)
#define GSV2K11_TXDIG_set_TX_HDMI_MODE_MAN(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xA5, 0x40, 0x6, val)
#define GSV2K11_TXDIG_set_DCFIFO_RESET(gsv_config, port, val)                        AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xA6, 0x20, 0x5, val)
#define GSV2K11_TXDIG_set_DCFIFO_RESET_ON_LOCK(gsv_config, port, val)                AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xA6, 0x10, 0x4, val)
#define GSV2K11_TXDIG_set_TDM_DESER_NUM_PINS(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xB0, 0xC, 2, val)
#define GSV2K11_TXDIG_set_TDM_DESER_NUM_SLOT(gsv_config, port, val)                  AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xB3, 0x3F, 0, val)
#define GSV2K11_TXDIG_set_TDM_DESER_NUM_CH(gsv_config, port, val)                    AvHalI2cWriteField8(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xB4, 0x3F, 0, val)
#define GSV2K11_TXDIG_set_DSD_EN(gsv_config,port, val)                              AvHalI2cWriteField32BE(gsv_config,GSV2K11_TXDIG_MAP_ADDR(port), 0xDA, 0xFF, 0xFF, 0, 4, val)
#endif
